### ISSUE TITLE
Long term internet shortage = severe memory and thread leaks?

### ISSUE THREAD

**Issue by NotGGhost** [NotGGhost/jSkype#20]
Last stacktrace after 20k plus lines of failed to reconnect lines.

Error: Connection timed out: connect
URL: https://client-s.gateway.messenger.live.com/v1/users/ME/endpoints/SELF/subscriptions/0/poll
Exception in thread "Thread-162913" java.lang.OutOfMemoryError: GC overhead limit exceeded
	at java.lang.String.split(String.java:2365)
	at java.lang.String.split(String.java:2410)
	at xyz.gghost.jskype.internal.auth.Auth.postData(Auth.java:33)
	at xyz.gghost.jskype.internal.auth.Auth.login(Auth.java:63)
	at xyz.gghost.jskype.SkypeAPI.login(SkypeAPI.java:75)
	at xyz.gghost.jskype.internal.packet.PacketBuilder.makeRequest(PacketBuilder.java:86)
	at xyz.gghost.jskype.internal.threads.Poller.poll(Poller.java:61)
	at xyz.gghost.jskype.internal.threads.Poller.access$000(Poller.java:24)
	at xyz.gghost.jskype.internal.threads.Poller$1.run(Poller.java:39)
Exception in thread "Thread-115749" java.lang.OutOfMemoryError: GC overhead limit exceeded
Exception in thread "Thread-189784" java.lang.OutOfMemoryError: GC overhead limit exceeded
Exception in thread "Thread-93798" java.lang.OutOfMemoryError: GC overhead limit exceeded
Exception in thread "Thread-138578" java.lang.OutOfMemoryError: GC overhead limit exceeded
Exception in thread "Thread-191178" java.lang.OutOfMemoryError: GC overhead limit exceeded
Exception in thread "Thread-117809"

**Comment by SpongyBacon** [comment]
That can't be good ;s

**Comment by NotGGhost** [comment]
Might not be an issue with the "new" poller

**Comment by NotGGhost** [comment]
Some people are reporting it happens randomly with 4-BETA. The time period it takes to crash is unknown, although I was pretty certain the memory leak was tackled.
